### ISSUE TITLE
Update bundler?

### ISSUE THREAD

**Issue by opoudjis** [metanorma/metanorma-build-scripts#10]
We don't fail Travis builds if the latest version of Ruby fails, but the ruby head build, Travis Ruby 2.6.*, is now failing because we're using an obsolete version of Builder:

````
Bundler could not find compatible versions for gem "bundler":
  In Gemfile:
    bundler (~> 2.0.1)
  Current Bundler version:
    bundler (2.1.0.pre.1)
This Gemfile requires a different version of Bundler.
Perhaps you need to update Bundler by running `gem install bundler`?
Could not find gem 'bundler (~> 2.0.1)' in any of the relevant sources:
  the local ruby installation
The command "bundle update" failed and exited with 6 during .
````

Should we globally switch to `bundler ~> 2`?

**Comment by CAMOBAP795** [comment]
@opoudjis is there a possible a backward compatibility issue?

**Comment by ronaldtse** [comment]
@opoudjis we can just remove the last two lines in Gemfile.lock:

```ruby
BUNDLED WITH
   1.17.3
```

And it will run fine with either bundler version.

**Comment by opoudjis** [comment]
@CAMOBAP795 I don't know anything about Bundler, so I can't answer the question.

@ronaldtse The file is `BUNDLED WITH 2.0.1`, and for half the gems, Gemfile.lock is not even included. That is not a solution, and it is sad that people in bundler are actually suggesting it as one. 

Bundler is up to 2.0.2. I strongly suggest we move to `bundler ~> 2`.

**Comment by ronaldtse** [comment]
> Bundler is up to 2.0.2. I strongly suggest we move to bundler ~> 2.

Sure, let's do it. I believe we meet the prerequisites for it:

---
Before you upgrade to Bundler 2, make sure you have the right Ruby and RubyGems. You need to be using Ruby 2.3.0 or higher, and you need to have RubyGems 2.5.0 or higher.

You can check your Ruby version by running ruby --version, and you can check your RubyGems version by running gem --version. If you need to upgrade Ruby, use your ruby version manager’s instructions. If you need to upgrade RubyGems, run gem update --system.

---

**Comment by CAMOBAP795** [comment]
@ronaldtse @opoudjis just to be on the same page are this task for CI configuration or for gemspec too?

**Comment by opoudjis** [comment]
Clearly for CI config; it does in fact apply to gemspec as well, but I'll change those manually. Assigning myself ticket as well.

**Comment by CAMOBAP795** [comment]
I will work on it

**Comment by CAMOBAP795** [comment]
@ronaldtse could you please check those PRs once they are ok, I will proceed with this one

 - https://github.com/metanorma/mn-itu-docs/pull/4
 - https://github.com/metanorma/ogc-tcpnp/pull/8/
 - https://github.com/metanorma/unece-cefact-plenary-2018-6/pull/4/
 -https://github.com/metanorma/csd-public-documents/pull/5

**Comment by CAMOBAP795** [comment]
Update: Generally most of the repose green, but for some, I have issues which not related to PR

Not fixed
 - [ ] metanorma/relaton-cli#233 - cannot load such file -- relaton/cli/yaml_convertor_new

Fixed
 - [x] metanorma/iso690render#9 - undefined method `parse' for Iso690Render:Module
 - [x] metanorma/metanorma-rsd#178 - OSX node error: SyntaxError: Unexpected token (
 - [x] metanorma/metanorma-csand#14 - OSX node error: SyntaxError: Unexpected token (
 - [x] metanorma/relaton-server-csd#12 - missing Gemfile

**Comment by CAMOBAP795** [comment]
Merged:
 - https://github.com/metanorma/cnccs/pull/4
 - https://github.com/metanorma/csa-ccm-tools/pull/9
 - https://github.com/metanorma/csd-public-documents/pull/6
 - https://github.com/metanorma/gb-agencies/pull/2
 - https://github.com/metanorma/html2doc/pull/29
 - https://github.com/metanorma/relaton-iec/pull/10
 - https://github.com/metanorma/relaton-ietf/pull/23
 - https://github.com/metanorma/iev/pull/12
 - https://github.com/metanorma/relaton-iso/pull/46
 - https://github.com/metanorma/isodoc-rice/pull/10
 - https://github.com/metanorma/isodoc/pull/106
 - https://github.com/metanorma/isoics/pull/6
 - https://github.com/metanorma/relaton-itu/pull/16
 - https://github.com/metanorma/mathml2asciimath/pull/5
 - https://github.com/metanorma/metanorma-acme/pull/7
 - https://github.com/metanorma/metanorma-cli/pull/95
 - https://github.com/metanorma/metanorma-csand/pull/14
 - https://github.com/metanorma/metanorma-csd/pull/82
 - https://github.com/metanorma/metanorma-gb/pull/101
 - https://github.com/metanorma/metanorma-ietf/pull/31
 - https://github.com/metanorma/metanorma-itu/pull/12
 - https://github.com/metanorma/metanorma-m3d/pull/16
 - https://github.com/metanorma/metanorma-mpfd/pull/18
 - https://github.com/metanorma/metanorma-nist/pull/137
 - https://github.com/metanorma/metanorma-ogc/pull/38
 - https://github.com/metanorma/metanorma-rsd/pull/23
 - https://github.com/metanorma/metanorma-sample/pull/8
 - https://github.com/metanorma/metanorma-unece/pull/20
 - https://github.com/metanorma/metanorma-vsd/pull/6
 - https://github.com/metanorma/metanorma/pull/69
 - https://github.com/metanorma/mn-ogc-documents/pull/4
 - https://github.com/metanorma/relaton-nist/pull/28
 - https://github.com/metanorma/ogc-tcpnp/pull/9
 - https://github.com/metanorma/ogc-wfs/pull/5
 - https://github.com/metanorma/omml2mathml/pull/10
 - https://github.com/metanorma/relaton-bib/pull/4
 - https://github.com/metanorma/relaton-server-csd/pull/2
 - https://github.com/metanorma/reverse_asciidoctor/pull/18
 - https://github.com/metanorma/unece-cefact-plenary-2018-6/pull/5
 - https://github.com/metanorma/unicode2latex/pull/5
 - https://github.com/metanorma/metanorma-iso/pull/273

Blocked:
 - https://github.com/metanorma/iso690render/pull/2
 - https://github.com/metanorma/relaton-cli/pull/56
 - https://github.com/metanorma/relaton/pull/45

**Comment by opoudjis** [comment]
@CAMOBAP795 I am unblocking relaton-cli, was in the middle of major refactor
